 name: Test
 on:
   push:
    branches:
     - master
 jobs:
    test:
      name: Test
      runs-on: ['ubuntu-latest', 'windows-latest', 'macos-latest']
      strategy:
      matrix:
        node: [ '12', '14', '16' ]
          name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: npm test
