 name: Test
 on:
   push:
    branches:
     - master
 jobs:
    test:
      name: Test
      runs-on: [ubuntu-latest, windows-latest, macos-latest]
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v1.1.0
          with:
            version:  [12.x, 14.x, 16.x]
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        - name: Checkout branch
          uses: actions/checkout@v2
          env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

        - name: Install dependencies
          run: yarn
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

        - name: Test coverage
          run: yarn cov
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
