 name: Deploy
 on:
   push:
    branches:
     - master
 jobs:
    gh-pages-deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v1.1.0
          with:
            version:  14.x
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        - name: Checkout branch
          uses: actions/checkout@v2
          env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

        - name: Clean install dependencies
          run: yarn
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

        - name: Build app
          run: npm run build
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      # - name: Name
      #   run: echo eris.js.org > eris.surge.sh
      #   env:
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

        - name: deploy
          uses: dswistowski/surge-sh-action@v1
          with:
           token: ${{ secrets.surge_token }}
           login: ${{ secrets.surge_login}}
           domain: eris.surge.sh
           project: ./src/.vuepress/dist
          env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
